name: Build and test

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Eval tuning build
      run: make clean && make EVAL_TUNING=yes

    - name: Sanitized debug build
      run: make clean && make SANITIZE=yes && ./debug_build/Stockfish-BAE go depth 20

    - name: Release build
      run: make clean && make RELEASE=yes && ./release_build/Stockfish-BAE go depth 20
